server:
  port: 9001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost
spring:
  application:
    name: DEPARTMENT-SERVICE
  h2:
    console:
      enable: true
  datasource:
    url: jdbc:h2:mem:testDept
    username: saDept
    password: 1234

    jpa:
      hibernate:
        ddl:
          auto: update
      show:
        sql: true