server:
  port: 9001

spring:
  application:
    name: DEPARTMENT-SERVICE
  h2:
    console:
      enable: true
  datasource:
    url: jdbc:h2:mem:testDept
    username: saDept
    password: 1234

    jpa:
      hibernate:
        ddl:
          auto: update
      show:
        sql: true