server:
  port: 9002

spring:
  application:
    name: USER-SERVICE
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: 1234

  jpa:
    hibernate:
      ddl:
        auto: update
    show:
      sql: true
